#define NETWORK_MODE_AUTOMATIC 2
#define NETWORK_MODE_GSM_ONLY 13
#define NETWORK_MODE_LTE_ONLY 35
#define NETWORK_MODE_GSM_AND_LTE_ONLY 51

#define PREFERRED_MODE_CAT_M 1
#define PREFERRED_MODE_NB_IOT 2
#define PREFERRED_MODE_CAT_M_AND_NB_IOT 3